#!/bin/sh
#
# phase1-up.sh - racoon phase1-up script hook
#
# Called by racoon after Phase 1 + Mode Config negotiation succeeds.
# Responsibilities:
#   1. Install split routes so only internal-network traffic enters the tunnel.
#   2. Register the tunnel's SPD policies via setkey.
#   3. Configure DNS (resolvers, split-DNS search domains) per server intent.
#
# Networks to tunnel come from the gateway (SPLIT_INCLUDE_CIDR).  A local
# NETWORKS fallback is provided for gateways that do not send this attribute.
#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2024-2026 Thomas Reim and the racoon-ipsec-tools contributors
# Part of rdratlos/racoon-ipsec-tools — https://github.com/rdratlos/racoon-ipsec-tools

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH

set -e

# --------------------------------------------------------------------------
# Logging — syslog (logger) + stderr for easy debugging
# --------------------------------------------------------------------------
log() {
	logger -t racoon-phase1-up "$*"
}

# --------------------------------------------------------------------------
# Guard — bail out early if the gateway did not assign an address.
# This can happen when the server rejects Mode Config (no pool, policy deny).
# --------------------------------------------------------------------------
if [ -z "${INTERNAL_ADDR4:-}" ] || [ -z "${LOCAL_ADDR:-}" ] || [ -z "${REMOTE_ADDR:-}" ]; then
	log "No Mode Config address assigned (internal=${INTERNAL_ADDR4:-?}) -- not installing routes or SPD"
	exit 0
fi

log "phase1 up: local=${LOCAL_ADDR:-?}:${LOCAL_PORT:-?} remote=${REMOTE_ADDR:-?}:${REMOTE_PORT:-?} internal=${INTERNAL_ADDR4}"

# --------------------------------------------------------------------------
# Determine the outbound network interface.
# We need the real interface (wlan0, eth0, …) to pin source-address
# selection and attach the /32 auxiliary address.
# --------------------------------------------------------------------------
IFACE=$(ip -4 route get "$REMOTE_ADDR" 2>/dev/null \
    | awk '{for (i = 1; i <= NF; i++) if ($i == "dev") print $(i + 1)}')
if [ -z "${IFACE:-}" ]; then
	log "Cannot determine outbound interface for $REMOTE_ADDR -- not installing SPD"
	exit 0
fi

# --------------------------------------------------------------------------
# Collect the set of internal networks to route through the tunnel.
# Priority: gateway-sent SPLIT_INCLUDE_CIDR > UNITY internal_nets
#           > hardcoded NETWORKS fallback (for legacy gateways).
# --------------------------------------------------------------------------
NETWORKS="${SPLIT_INCLUDE_CIDR:-}"
if [ -z "$NETWORKS" ]; then
	# Some racoon builds export internal networks via SPLIT_INCLUDE
	NETWORKS="${SPLIT_INCLUDE:-}"
fi
if [ -z "$NETWORKS" ]; then
	# Hardcoded fallback — matches server sample (10.0.12.0/24).
	# Override in your site-local copy or /etc/racoon/overrides.
	NETWORKS="10.0.12.0/24"
	log "WARNING: No split routes from gateway; using hardcoded NETWORKS fallback"
fi

if [ -z "$NETWORKS" ]; then
	log "No internal networks known -- nothing to tunnel"
	exit 0
fi

# --------------------------------------------------------------------------
# Pin INTERNAL_ADDR4 as a /32 auxiliary address on the real interface,
# and install per-network routes with src=INTERNAL_ADDR4.
#
# Why?  Linux selects the source address from the routing table.  By
# advertising INTERNAL_ADDR4 as a local address and adding explicit src=
# routes, application traffic to internal networks will propose the
# (INTERNAL_ADDR4 → network) selector pair that matches the SPD below.
# Without this, traffic uses the interface's primary address and silently
# bypasses the IPsec tunnel.
# --------------------------------------------------------------------------
ip addr replace "${INTERNAL_ADDR4}/32" dev "$IFACE"
for net in $NETWORKS; do
	ip route replace "$net" dev "$IFACE" src "$INTERNAL_ADDR4"
done
log "internal=${INTERNAL_ADDR4} configured as /32 on $IFACE; routes installed for: $NETWORKS"

# --------------------------------------------------------------------------
# SPD (Security Policy Database) via setkey.
#
# For each internal network we install a bidirectional pair:
#   outbound: (INTERNAL_ADDR4/32 → net) → tunnel
#   inbound:  (net → INTERNAL_ADDR4/32) → tunnel
#
# We write to spd.conf for human inspection, then pipe to setkey.
# --------------------------------------------------------------------------
LOCAL="${LOCAL_ADDR}"
REMOTE="${REMOTE_ADDR}"
if [ "${LOCAL_PORT:-500}" != "500" ]; then
	# NAT-T in use — encode negotiated ports into tunnel endpoints
	LOCAL="${LOCAL}[${LOCAL_PORT}]"
	REMOTE="${REMOTE}[${REMOTE_PORT}]"
fi

SPD_CONF="/etc/racoon/spd.conf"
umask 077
{
	echo "#!/usr/sbin/setkey -f"
	echo "# Generated by phase1-up.sh on $(date -Is)"
	echo "# DO NOT EDIT — regenerated on every phase1-up"
	echo "spdflush;"
	for net in $NETWORKS; do
		echo "spdadd ${INTERNAL_ADDR4}/32 $net any -P out ipsec esp/tunnel/${LOCAL}-${REMOTE}/require;"
		echo "spdadd $net ${INTERNAL_ADDR4}/32 any -P in  ipsec esp/tunnel/${REMOTE}-${LOCAL}/require;"
	done
} > "$SPD_CONF.new"
mv "$SPD_CONF.new" "$SPD_CONF"

setkey -f "$SPD_CONF"
log "SPD installed ($NETWORKS) via tunnel ${LOCAL}-${REMOTE} (see $SPD_CONF)"

# --------------------------------------------------------------------------
# DNS — detect the system's resolver and configure nameservers +
# split-DNS search domains as instructed by the VPN gateway.
# --------------------------------------------------------------------------
detect_resolver() {
	if command -v resolvectl >/dev/null 2>&1 || command -v resctl >/dev/null 2>&1; then
		if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
			echo "systemd-resolved"
			return
		fi
	fi
	if command -v nmcli >/dev/null 2>&1; then
		if systemctl is-active --quiet NetworkManager 2>/dev/null; then
			echo "networkmanager"
			return
		fi
	fi
	if command -v resolvconf >/dev/null 2>&1; then
		if [ -e /run/resolvconf ]; then
			echo "resolvconf"
			return
		fi
	fi
	if command -v dnsmasq >/dev/null 2>&1; then
		if pgrep -x dnsmasq >/dev/null 2>&1; then
			echo "dnsmasq"
			return
		fi
	fi
	echo "fallback"
}

RESOLVER=$(detect_resolver)
log "Detected DNS resolver: ${RESOLVER}"

DNS_SERVERS="${INTERNAL_DNS4_LIST:-$INTERNAL_DNS4}"
if [ -z "$DNS_SERVERS" ]; then
	log "No DNS servers from gateway; skipping DNS setup"
	DNS_SERVERS=""
fi

# Collect split-DNS search domains (UNITY or Mode Config)
SEARCH_DOMAINS="${INTERNAL_SPLITDNS_DOMAINS:-}"
if [ -z "$SEARCH_DOMAINS" ] && [ -n "${DEFAULT_DOMAIN:-}" ]; then
	SEARCH_DOMAINS="$DEFAULT_DOMAIN"
fi

# ---- resolver-specific setup ----
setup_systemd_resolved_dns() {
	local ifname="$1" dns_list="$2" domains="$3"
	[ -z "$dns_list" ] && [ -z "$domains" ] && return 0
	local rescmd="resolvectl"
	command -v resolvectl >/dev/null 2>&1 || rescmd="resctl"

	if [ -n "$dns_list" ]; then
		local dns_csv; dns_csv=$(echo "$dns_list" | tr ' ' ',')
		"$rescmd" dns "${ifname}" $dns_csv 2>/dev/null || \
			log "resolvectl dns failed for ${ifname}"
	fi
	if [ -n "$domains" ]; then
		local d; d=$(echo "$domains" | tr ',' ' ')
		"$rescmd" domain "${ifname}" $d 2>/dev/null || \
			log "resolvectl domain failed for ${ifname}"
		# route-only: only resolve for these domains, not as default DNS
		"$rescmd" default-route "${ifname}" false 2>/dev/null || true
	fi
}

setup_networkmanager_dns() {
	local conn="$1" dns_list="$2" domains="$3"
	[ -z "$dns_list" ] && [ -z "$domains" ] && return 0
	# Find the NM connection profile for the active interface carrying
	# the VPN traffic.  We modify its DNS directly so NM propagates the
	# split-DNS to /etc/resolv.conf.
	local active_conn
	active_conn=$(nmcli -t -f NAME,DEVICE conn show --active 2>/dev/null \
	    | grep ":${IFACE}$" | head -n1 | cut -d: -f1) || true
	if [ -z "$active_conn" ]; then
		log "Cannot determine NM connection for $IFACE; falling back to resolv.conf"
		setup_fallback_dns "$dns_list" "$domains"
		echo "fallback" > /run/racoon/dns-method 2>/dev/null || true
		return
	fi
	# Back up current DNS so phase1-down can restore.
	mkdir -p /run/racoon
	nmcli -t -f ipv4.dns,ipv4.dns-search conn show "$active_conn" \
	    2>/dev/null > /run/racoon/nm-dns-backup.txt || true
	# Replace DNS settings on the active connection.
	if [ -n "$dns_list" ]; then
		nmcli conn modify "$active_conn" ipv4.dns "$(echo "$dns_list" | tr ' ' ',')" >/dev/null 2>&1 || true
	fi
	if [ -n "$domains" ]; then
		nmcli conn modify "$active_conn" ipv4.dns-search "$(echo "$domains" | tr ',' ';')" >/dev/null 2>&1 || true
	fi
	nmcli conn down "$active_conn" >/dev/null 2>&1 || true
	nmcli conn up "$active_conn" >/dev/null 2>&1 || true
	echo "networkmanager-active" > /run/racoon/dns-method 2>/dev/null || true
	log "NM DNS updated on connection '$active_conn': dns=$dns_list domains=$domains"
}

setup_resolvconf_dns() {
	local dns_list="$1" domains="$2" iface="$3"
	[ -z "$dns_list" ] && return 0
	{
		echo "# Generated by racoon phase1-up on $(date)"
		[ -n "$domains" ] && echo "search $(echo "$domains" | tr ',' ' ')"
		for dns in $dns_list; do echo "nameserver ${dns}"; done
	} | resolvconf -a "${iface}.racoon" 2>/dev/null || \
		log "resolvconf failed; falling back"
}

setup_dnsmasq_dns() {
	local dns_list="$1" domains="$2"
	[ -d /etc/dnsmasq.d ] || return 0
	{
		echo "# Generated by racoon phase1-up on $(date)"
		for dns in $dns_list; do echo "server=${dns}"; done
		[ -n "$domains" ] && echo "domain=$(echo "$domains" | tr ',' ' ')"
	} > /etc/dnsmasq.d/racoon-vpn
	killall -HUP dnsmasq 2>/dev/null || true
}

setup_fallback_dns() {
	local dns_list="$1" domains="$2"
	log "WARNING: no supported resolver found; writing /etc/resolv.conf directly"
	cp /etc/resolv.conf /etc/resolv.conf.racoon.bak 2>/dev/null || true
	{
		echo "# Generated by racoon phase1-up on $(date)"
		[ -n "$domains" ] && echo "search $(echo "$domains" | tr ',' ' ')"
		for dns in $dns_list; do echo "nameserver ${dns}"; done
	} > /etc/resolv.conf
}

case "$RESOLVER" in
	systemd-resolved)
		setup_systemd_resolved_dns "${IFACE}" "$DNS_SERVERS" "$SEARCH_DOMAINS"
		;;
	networkmanager)
		setup_networkmanager_dns "racoon-vpn" "$DNS_SERVERS" "$SEARCH_DOMAINS"
		;;
	resolvconf)
		setup_resolvconf_dns "$DNS_SERVERS" "$SEARCH_DOMAINS" "${IFACE}"
		;;
	dnsmasq)
		setup_dnsmasq_dns "$DNS_SERVERS" "$SEARCH_DOMAINS"
		;;
	fallback)
		[ -n "$DNS_SERVERS" ] && setup_fallback_dns "$DNS_SERVERS" "$SEARCH_DOMAINS"
		;;
esac

if [ -n "$SEARCH_DOMAINS" ]; then
	log "Split-DNS search domains applied: ${SEARCH_DOMAINS}"
fi

log "VPN setup complete: routes=$NETWORKS dns=${DNS_SERVERS:-none} domains=${SEARCH_DOMAINS:-none}"
exit 0