#!/bin/sh
#
# phase1-up.sh -- invoked by racoon after a successful Phase 1 +
# Mode Config negotiation (see "script ... phase1_up;" in
# gateway.conf). This is where the SPD trap/tunnel policies for the
# three protected networks actually get built, using the pool address
# (INTERNAL_ADDR4, e.g. 192.168.66.5) the gateway just assigned as the
# selector source.
#
# This is different from src/racoon/samples/roadwarrior/client/phase1-up.sh
# (the shipped mode_cfg sample): that one does a full-tunnel default
# route + /etc/resolv.conf rewrite. This one is a split-tunnel for a
# named, fixed set of networks and leaves the default route/DNS alone
# -- but it still needs the pool address to actually be usable as a
# *source* address, for the same reason the full-tunnel sample brings
# up an alias interface: our SPD "out" selector below requires the
# packet's source to be exactly INTERNAL_ADDR4/32 (that's what the
# gateway expects to see proposed in Quick Mode for this client
# identity). Without configuring INTERNAL_ADDR4 as a real local address
# and steering the three routes to prefer it as source, ordinary
# application traffic (ping, SSSD, autofs) keeps using the laptop's
# real WLAN address as source, which never matches the policy -- no
# ACQUIRE, no Quick Mode, and the packet falls through to the plain
# on-link route resolve-gateway.sh installed for reverse-path-filter
# purposes, then dies as an ARP timeout for a host that was never
# really on the WLAN segment. (Symptom actually seen: Phase 1 + Mode
# Config completed and stayed up via DPD, but no ping ever got
# through -- "ip route" showed the three protected networks as plain
# on-link routes with no matching local source address.)
#
# Why this can't happen earlier (e.g. once, at boot, like the old
# static-subnet revision of this sample did): the pool address is
# assigned fresh by the gateway's mode_cfg exchange and isn't known
# until this hook fires, so there is nothing to pre-install a kernel
# ACQUIRE trap policy for beforehand -- resolve-gateway.sh's active
# "establish-sa" priming call is what gets Phase 1 (and this hook)
# running in the first place.

NETWORKS="192.168.66.0/24 192.168.83.0/24 10.66.0.0/24"
SPD_CONF="/etc/racoon/spd.conf"   # written here for inspection/reload, not authoritative

logger -t racoon-phase1-up \
    "phase1 up: local=${LOCAL_ADDR:-?}:${LOCAL_PORT:-?} remote=${REMOTE_ADDR:-?}:${REMOTE_PORT:-?} internal=${INTERNAL_ADDR4:-?}"

if [ -z "${INTERNAL_ADDR4:-}" ] || [ -z "${LOCAL_ADDR:-}" ] || [ -z "${REMOTE_ADDR:-}" ]; then
    logger -t racoon-phase1-up \
        "no mode_cfg pool address assigned -- not installing SPD (is mode_cfg accepted on the gateway for this login?)"
    exit 0
fi

IFACE=$(ip -4 route get "$REMOTE_ADDR" 2>/dev/null \
    | awk '{for (i = 1; i <= NF; i++) if ($i == "dev") print $(i + 1)}')
if [ -z "${IFACE:-}" ]; then
    logger -t racoon-phase1-up "cannot determine outbound interface for $REMOTE_ADDR -- not installing SPD"
    exit 0
fi

# Make INTERNAL_ADDR4 a real local address and the preferred source for
# the three protected networks, so ordinary application traffic
# actually proposes/matches the (INTERNAL_ADDR4, network) selector pair
# below instead of silently missing the policy.
ip addr replace "${INTERNAL_ADDR4}/32" dev "$IFACE"
for net in $NETWORKS; do
    ip route replace "$net" dev "$IFACE" src "$INTERNAL_ADDR4"
done
logger -t racoon-phase1-up "internal=${INTERNAL_ADDR4} configured as local address on $IFACE, routes updated with matching src"

LOCAL="${LOCAL_ADDR}"
REMOTE="${REMOTE_ADDR}"
if [ "x${LOCAL_PORT:-500}" != "x500" ]; then
    # NAT-T: encode the negotiated ports into the tunnel endpoints too
    LOCAL="${LOCAL}[${LOCAL_PORT}]"
    REMOTE="${REMOTE}[${REMOTE_PORT}]"
fi

umask 077
{
    echo "#!/usr/sbin/setkey -f"
    echo "# Generated by phase1-up.sh on $(date -Is) -- do not edit by hand"
    echo "spdflush;"
    for net in $NETWORKS; do
        echo "spdadd ${INTERNAL_ADDR4}/32 $net any -P out ipsec esp/tunnel/${LOCAL}-${REMOTE}/require;"
        echo "spdadd $net ${INTERNAL_ADDR4}/32 any -P in  ipsec esp/tunnel/${REMOTE}-${LOCAL}/require;"
    done
} > "$SPD_CONF.new"
mv "$SPD_CONF.new" "$SPD_CONF"

setkey -f "$SPD_CONF"
logger -t racoon-phase1-up "SPD installed for internal=${INTERNAL_ADDR4} via tunnel ${LOCAL}-${REMOTE}"

exit 0
