#!/bin/sh
#
# resolve-gateway.sh -- bridge between a Dynamic-DNS VPN gateway and
# racoon's static, numeric-only configuration.
#
# racoon rejects hostnames in "remote" blocks (str2saddr() resolves with
# AI_NUMERICHOST) and setkey rejects them in tunnel-mode SPD endpoints
# (policy_parse.y, same restriction) -- both need literal IPs. Neither
# the VPN gateway's public address (Dynamic DNS) nor this laptop's own
# address (WLAN/DHCP roaming) is stable, so both are resolved here and
# baked into two generated files:
#
#   /etc/racoon/gateway.conf  -- the "remote <ip> { ... }" block
#   /etc/racoon/spd.conf      -- setkey trap ("require") policies for
#                                 the protected internal networks
#
# Run at boot, on every NetworkManager interface-up event, and on a
# timer (to catch a Dynamic DNS change even while the laptop stays on
# the same network). It is idempotent: if neither address changed since
# the last run, it does nothing -- so re-running it does not disturb an
# already-established tunnel.

set -eu

GATEWAY_FQDN="nepomuc.selfhost.eu"
NETWORKS="192.168.66.0/24 192.168.83.0/24 10.66.0.0/24"

RACOON_DIR="/etc/racoon"
STATE_DIR="/var/lib/racoon"
STATE_FILE="$STATE_DIR/gw-resolve.state"
GATEWAY_CONF="$RACOON_DIR/gateway.conf"
SPD_CONF="$RACOON_DIR/spd.conf"

log() {
    logger -t racoon-gw-resolve "$*" 2>/dev/null || echo "racoon-gw-resolve: $*" >&2
}

mkdir -p "$STATE_DIR"

GATEWAY_IP=$(getent ahostsv4 "$GATEWAY_FQDN" 2>/dev/null | awk '{print $1; exit}') || true
if [ -z "${GATEWAY_IP:-}" ]; then
    log "cannot resolve $GATEWAY_FQDN yet, keeping last known config"
    exit 0
fi

LOCAL_IP=$(ip -4 route get "$GATEWAY_IP" 2>/dev/null \
    | awk '{for (i = 1; i <= NF; i++) if ($i == "src") print $(i + 1)}')
if [ -z "${LOCAL_IP:-}" ]; then
    log "no route to $GATEWAY_IP yet, keeping last known config"
    exit 0
fi

NEW_STATE="${GATEWAY_IP}/${LOCAL_IP}"
OLD_STATE=$(cat "$STATE_FILE" 2>/dev/null || true)

if [ "$NEW_STATE" = "$OLD_STATE" ]; then
    exit 0   # nothing changed -- do not touch a working tunnel/policies
fi

log "gateway=$GATEWAY_IP local=$LOCAL_IP (was: ${OLD_STATE:-none}) -- refreshing config"

umask 077
{
    echo "# Generated by resolve-gateway.sh on $(date -Is) -- do not edit by hand"
    echo "remote $GATEWAY_IP"
    echo "{"
    echo "    exchange_mode           main;"
    echo "    my_identifier            asn1dn;"
    echo "    peers_identifier         asn1dn;"
    echo "    verify_identifier        on;"
    echo ""
    echo "    certificate_type         x509 \"client.crt\" \"client.key\";"
    echo "    ca_type                  x509 \"ca.crt\";"
    echo ""
    echo "    passive                  off;"
    echo "    ike_frag                 on;"
    echo "    nat_traversal             on;"
    echo "    dpd_delay                20;"
    echo "    dpd_retry                 5;"
    echo "    dpd_maxfail                3;"
    echo "    proposal_check             claim;"
    echo "    lifetime                   time 8 hours;"
    echo ""
    echo "    script \"/etc/racoon/phase1-up.sh\"   phase1_up;"
    echo "    script \"/etc/racoon/phase1-down.sh\" phase1_down;"
    echo ""
    echo "    proposal {"
    echo "        encryption_algorithm    aes 256;"
    echo "        hash_algorithm          sha256;"
    echo "        authentication_method   rsasig;"
    echo "        dh_group                 14;"
    echo "    }"
    echo "}"
} > "$GATEWAY_CONF.new"
mv "$GATEWAY_CONF.new" "$GATEWAY_CONF"

{
    echo "#!/usr/sbin/setkey -f"
    echo "# Generated by resolve-gateway.sh on $(date -Is) -- do not edit by hand"
    echo "spdflush;"
    for net in $NETWORKS; do
        echo "spdadd 0.0.0.0/0 $net any -P out ipsec esp/tunnel/${LOCAL_IP}-${GATEWAY_IP}/require;"
        echo "spdadd $net 0.0.0.0/0 any -P in  ipsec esp/tunnel/${GATEWAY_IP}-${LOCAL_IP}/require;"
    done
} > "$SPD_CONF.new"
mv "$SPD_CONF.new" "$SPD_CONF"

setkey -f "$SPD_CONF"
echo "$NEW_STATE" > "$STATE_FILE"

# Make racoon pick up the new/changed remote block.
if pidof racoon >/dev/null 2>&1 && command -v racoonctl >/dev/null 2>&1; then
    racoonctl reload-config >/dev/null 2>&1 || kill -HUP "$(pidof racoon)" 2>/dev/null || true

    # Best-effort: ask racoon to start Phase 1 right away instead of
    # waiting for the first real SSSD/autofs packet to trigger the
    # kernel ACQUIRE. Deliberately NOT "racoonctl vc": that shortcut
    # blocks waiting for a mode_cfg completion event we never send in
    # this (non-mode_cfg) setup and would hang. The low-level
    # "establish-sa" without "-w" fires the request and returns
    # immediately.
    racoonctl es isakmp inet "$LOCAL_IP" "$GATEWAY_IP" >/dev/null 2>&1 || true
fi

log "done"
