#!/bin/sh
#
# resolve-gateway.sh -- bridge between a Dynamic-DNS VPN gateway and
# racoon's static, numeric-only configuration.
#
# racoon rejects hostnames in "remote" blocks (str2saddr() resolves with
# AI_NUMERICHOST) and setkey rejects them in tunnel-mode SPD endpoints
# (policy_parse.y, same restriction) -- both need literal IPs. Neither
# the VPN gateway's public address (Dynamic DNS) nor this laptop's own
# address (WLAN/DHCP roaming) is stable, so both are resolved here and
# baked into two generated files:
#
#   /etc/racoon/gateway.conf  -- the "remote <ip> { ... }" block
#   /etc/racoon/spd.conf      -- setkey trap ("require") policies for
#                                 the protected internal networks
#
# Run at boot, on every NetworkManager interface-up event, and on a
# timer (to catch a Dynamic DNS change even while the laptop stays on
# the same network).
#
# The SPD trap policies are reinstalled on *every* run, unconditionally
# -- this is deliberately self-healing: if anything external flushed
# the SPD (a racoon restart, a manual "setkey -F" while debugging, a
# crash), the next scheduled/triggered run puts the policies back
# without anyone noticing they were gone. A stale "nothing changed, so
# skip setkey" optimization keyed only on gateway/local IP would miss
# exactly that case -- the addresses haven't changed, but the kernel's
# SPD is still empty. "setkey -f" flush-then-readd is cheap and does
# not require a fresh Phase 1 (an already-negotiated SA is looked up by
# the kernel again as soon as a matching policy exists).
#
# gateway.conf regeneration, racoon's config reload and the priming
# "establish-sa" call, however, only happen when the gateway's or the
# local address actually changed -- no need to bounce Phase 1 every 10
# minutes just because the timer fired.

set -eu

GATEWAY_FQDN="nepomuc.selfhost.eu"
NETWORKS="192.168.66.0/24 192.168.83.0/24 10.66.0.0/24"

RACOON_DIR="/etc/racoon"
STATE_DIR="/var/lib/racoon"
STATE_FILE="$STATE_DIR/gw-resolve.state"
GATEWAY_CONF="$RACOON_DIR/gateway.conf"
SPD_CONF="$RACOON_DIR/spd.conf"

log() {
    logger -t racoon-gw-resolve "$*" 2>/dev/null || echo "racoon-gw-resolve: $*" >&2
}

mkdir -p "$STATE_DIR"

GATEWAY_IP=$(getent ahostsv4 "$GATEWAY_FQDN" 2>/dev/null | awk '{print $1; exit}') || true
if [ -z "${GATEWAY_IP:-}" ]; then
    log "cannot resolve $GATEWAY_FQDN yet, keeping last known config"
    exit 0
fi

ROUTE_INFO=$(ip -4 route get "$GATEWAY_IP" 2>/dev/null)
LOCAL_IP=$(echo "$ROUTE_INFO" | awk '{for (i = 1; i <= NF; i++) if ($i == "src") print $(i + 1)}')
IFACE=$(echo "$ROUTE_INFO" | awk '{for (i = 1; i <= NF; i++) if ($i == "dev") print $(i + 1)}')
if [ -z "${LOCAL_IP:-}" ] || [ -z "${IFACE:-}" ]; then
    log "no route to $GATEWAY_IP yet, keeping last known config"
    exit 0
fi

NEW_STATE="${GATEWAY_IP}/${LOCAL_IP}/${IFACE}"
OLD_STATE=$(cat "$STATE_FILE" 2>/dev/null || true)
ADDR_CHANGED=1
[ "$NEW_STATE" = "$OLD_STATE" ] && ADDR_CHANGED=0

# --- routes + SPD trap policies: always reinstalled, unconditionally
#
# Without an explicit route to each protected network via $IFACE,
# strict reverse-path filtering (net.ipv4.conf.*.rp_filter=1, common
# distro default) drops decrypted inbound packets as a "martian
# source": the kernel can find no route that would send a reply back
# to e.g. 10.66.0.6 out the interface it arrived on, so it silently
# discards the packet *after* successful IPsec decapsulation -- ESP
# byte counters in "setkey -D"/"ip -s xfrm state" increase normally,
# XfrmIn* counters in /proc/net/xfrm_stat stay at 0 (decapsulation
# itself is fine), but the packet never reaches the socket. Confirm
# with "sysctl -w net.ipv4.conf.all.log_martians=1" and watch
# "journalctl -k" for "martian source" while pinging.
#
# "ip route replace" (not "add") so re-running this after the
# interface name changed (a different WLAN adapter, roaming) cleanly
# updates rather than erroring out on a duplicate route.
for net in $NETWORKS; do
    ip route replace "$net" dev "$IFACE"
done

umask 077
{
    echo "#!/usr/sbin/setkey -f"
    echo "# Generated by resolve-gateway.sh on $(date -Is) -- do not edit by hand"
    echo "spdflush;"
    for net in $NETWORKS; do
        echo "spdadd 0.0.0.0/0 $net any -P out ipsec esp/tunnel/${LOCAL_IP}-${GATEWAY_IP}/require;"
        echo "spdadd $net 0.0.0.0/0 any -P in  ipsec esp/tunnel/${GATEWAY_IP}-${LOCAL_IP}/require;"
    done
} > "$SPD_CONF.new"
mv "$SPD_CONF.new" "$SPD_CONF"

setkey -f "$SPD_CONF"
log "gateway=$GATEWAY_IP local=$LOCAL_IP dev=$IFACE -- routes + SPD trap policies (re)installed"

if [ "$ADDR_CHANGED" -eq 0 ]; then
    exit 0   # address unchanged -- no need to touch racoon/Phase 1
fi

log "gateway=$GATEWAY_IP local=$LOCAL_IP (was: ${OLD_STATE:-none}) -- address changed, refreshing gateway.conf"

# --- remote block: only rewritten/reloaded when the address changed -
{
    echo "# Generated by resolve-gateway.sh on $(date -Is) -- do not edit by hand"
    echo "remote $GATEWAY_IP"
    echo "{"
    echo "    exchange_mode           main;"
    echo "    my_identifier            asn1dn;"
    echo "    peers_identifier         asn1dn;"
    echo "    verify_identifier        on;"
    echo ""
    echo "    certificate_type         x509 \"client.crt\" \"client.key\";"
    echo "    ca_type                  x509 \"ca.crt\";"
    echo ""
    echo "    passive                  off;"
    echo "    ike_frag                 on;"
    echo "    nat_traversal             on;"
    echo "    dpd_delay                20;"
    echo "    dpd_retry                 5;"
    echo "    dpd_maxfail                3;"
    echo "    proposal_check             claim;"
    echo "    lifetime                   time 8 hours;"
    echo ""
    echo "    script \"/etc/racoon/phase1-up.sh\"   phase1_up;"
    echo "    script \"/etc/racoon/phase1-down.sh\" phase1_down;"
    echo ""
    echo "    proposal {"
    echo "        encryption_algorithm    aes 256;"
    echo "        hash_algorithm          sha256;"
    echo "        authentication_method   rsasig;"
    echo "        dh_group                 14;"
    echo "    }"
    echo "}"
} > "$GATEWAY_CONF.new"
mv "$GATEWAY_CONF.new" "$GATEWAY_CONF"

echo "$NEW_STATE" > "$STATE_FILE"

# Make racoon pick up the new/changed remote block.
if pidof racoon >/dev/null 2>&1 && command -v racoonctl >/dev/null 2>&1; then
    racoonctl reload-config >/dev/null 2>&1 || kill -HUP "$(pidof racoon)" 2>/dev/null || true

    # Best-effort: ask racoon to start Phase 1 right away instead of
    # waiting for the first real SSSD/autofs packet to trigger the
    # kernel ACQUIRE. Deliberately NOT "racoonctl vc": that shortcut
    # blocks waiting for a mode_cfg completion event we never send in
    # this (non-mode_cfg) setup and would hang. The low-level
    # "establish-sa" without "-w" fires the request and returns
    # immediately.
    racoonctl es isakmp inet "$LOCAL_IP" "$GATEWAY_IP" >/dev/null 2>&1 || true
fi

log "done"
